### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by domesticmouse** [PoojaB26/FlutterBasicWidgets#1]
Hey Pooja,

I cloned your repo, and then ran `flutter run` in the checkout directory and it broke in a rather spectacular fashion: https://github.com/flutter/flutter/issues/22294

Any chance of adding the expected commands to get started with your repo to your `README.md`? 

Thanks!

**Comment by PoojaB26** [comment]
Thanks for letting me know. You have to run <code> flutter create . </code> but make sure your root directory is renamed as all_lowercase_with_underscore  instead of FlutterBasicWidgets. 

Closing this issue here. If you still have problems, you are free to reopen.

**Comment by PoojaB26** [comment]
Added the information in the README.
