### ISSUE TITLE
Unknow property 'colors' in FlutterLogo widget

### ISSUE THREAD

**Issue by ChiragGrover** [PoojaB26/FlutterBasicWidgets#5]
Unknown property in Dart Pad. Not able to compile and run with this property.

After removing this colors property, i'm able to compile and run the code.

![image](https://user-images.githubusercontent.com/20610825/96362447-ff18ce80-114a-11eb-9e1c-62ba1081c4b8.png)

**Comment by PoojaB26** [comment]
Thank you for reporting. Probably it is removed from the new SDK update. I have updated the code in README and Dartpad! Happy learning! 💯
